version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can
  # use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool,
  # so you don't have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@3.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.16

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install gir1.2-gtk-3.0 gir1.2-wnck-3.0 gobject-introspection libcairo2-dev libgirepository1.0-dev python3-gi
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_ci.txt
      - run:
          name: check code
          command: |
            . venv/bin/activate
            python -m compileall wmectrl
            python -m pycodestyle wmectrl
            python -m flake8 wmectrl
            python -m build --outdir=dist .
            python -m pip install --verbose dist/*.whl
            python -m pip list
            python -m pip freeze
            ls -laR .
            python -m pip uninstall --yes --verbose wmectrl
