name: Python 3.11

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "python-build-test"
      uses: ./.github/actions/python-build-test
      with:
        python-version: "3.11"
        python-module: "wmectrl"

    - name: "python-build-test"
      uses: ./.github/actions/test-wmectrl
